name: End-to-end tests

on:
  push:
    branches:
      - "dev"
      - "!main"
      - "cypress-dev"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies for the client
      - name: Install dependencies for client
        working-directory: mern/client
        run: npm install

      # Start the server for testing
      - name: Start server
        working-directory: mern/server
        run: npm start

      # Wait for server to start
      - name: Wait for server to start
        run: sleep 10s

      # Run Cypress tests
      - name: Cypress run
        working-directory: mern/client
        run: |
          npm start &
          npx wait-on http://localhost:5173/
          npx cypress run
        env:
          CYPRESS_CACHE_FOLDER: /tmp/cypress-cache
