name: End-to-end tests

on:
  push:
    branches:
      - "dev"
      - "!main"
      - "cypress-dev"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install dependencies for the server
      - name: Install dependencies for server
        working-directory: mern/server
        run: npm ci

      # Install dependencies for the client
      - name: Install dependencies for client
        working-directory: mern/client
        run: npm ci

      # Start the server for testing
      - name: Start server
        working-directory: mern/server
        run: npm start &

      # Wait for server to start
      - name: Wait for server to start
        run: sleep 10s

      # Start the client for testing
      - name: Start client
        working-directory: mern/client
        run: npm run dev

      # Run Cypress tests
      - name: Cypress run
        working-directory: mern/client
        run: |
          npx cypress run
        env:
          CYPRESS_CACHE_FOLDER: /tmp/cypress-cache
