name: End-to-end tests

on:
  push:
    branches:
      - "dev"
      - "!main"
      - "cypress-dev"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Install dependencies for the server
      - name: Install dependencies for server
        working-directory: mern/server
        run: npm ci

      # Install dependencies for the client
      - name: Install dependencies for client
        working-directory: mern/client
        run: npm ci

      # Start the server for testing
      - name: Start server
        working-directory: mern/server
        run: npm start &

      # Wait for server to start
      - name: Wait for server to start
        run: |
          echo "Waiting for server to start..."
          sleep 30s
          echo "Server should be ready now."

      # Start the client for testing
      - name: Start client
        working-directory: mern/client
        run: |
          echo "Starting client..."
          npm run dev &
          echo "Client should be starting..."

      # Install wait-on package
      - name: Install wait-on
        run: npm install wait-on@7.2.0

      # Wait for client to start
      - name: Wait for client to start
        run: |
          echo "Waiting for client to start..."
          npx wait-on http://localhost:3000/  # Update the port if needed
          echo "Client should be ready now."

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress

      # Run Cypress tests
      - name: Cypress run
        run: |
          npx cypress run
        env:
          CYPRESS_CACHE_FOLDER: /tmp/cypress-cache
