name: End-to-end tests

on:
  push:
    branches:
      - "dev"
      - "!main"
      - "cypress-dev"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start server in the background
        run: (cd mern/server && npm start &) # Start server in background
      - name: Start React app in the background (if needed)
        run: (cd mern/client && npm start &) # Start client in background (optional)

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: mern/client
